### ISSUE TITLE
NavBar overlap

### ISSUE THREAD

**Issue by rpmccarter** [partyfishgames/website#25]
When window is at an intermediate width (right before navbar collapses to dropdown menu), some of the navigation tabs overlap with the PartyFish logo.

<img width="891" alt="Screen Shot 2022-03-23 at 3 28 18 PM" src="https://user-images.githubusercontent.com/63772591/159785094-cadf4093-1efb-48e6-b570-ba69cf7adb6f.png">

**Comment by Dun-sin** [comment]
Hi, can i work on this?

**Comment by jgordley** [comment]
Solved by: [https://github.com/partyfishgames/website/pull/34](https://github.com/partyfishgames/website/pull/34)
